/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogItem: typeof import('./../components/BlogItem.vue')['default']
    BlogList: typeof import('./../components/BlogList.vue')['default']
    Home: typeof import('./../components/Home.vue')['default']
    PostItem: typeof import('./../components/PostItem.vue')['default']
    PostList: typeof import('./../components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./../components/TagList.vue')['default']
    TagPostList: typeof import('./../components/TagPostList.vue')['default']
  }
}
